trigger:
- main

pool: my-personal-computer

variables:
  buildConfiguration: 'Release'
  proyecto: 'MinimalAPIPeliculas/MinimalAPIPeliculas.csproj'

steps:
- task: UseDotNet@2
  displayName: 'Instalar .NET 9 SDK'
  inputs:
    packageType: 'sdk'
    version: '9.0.x'

- task: DotNetCoreCLI@2
  displayName: 'Restore'
  inputs:
    command: 'restore'
    projects: '$(proyecto)'

- task: DotNetCoreCLI@2
  displayName: 'Build'
  inputs:
    command: 'build'
    projects: '$(proyecto)'
    arguments: '--configuration $(buildConfiguration) --no-restore'

- task: DotNetCoreCLI@2
  displayName: 'Publish'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(proyecto)'
    arguments: '--configuration $(buildConfiguration) --no-restore --output $(Build.ArtifactStagingDirectory)/webapp --runtime win-x64 --self-contained'
    zipAfterPublish: false
    modifyOutputPath: false

- task: PublishBuildArtifacts@1
  displayName: 'Publicar artefactos'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)/webapp'
    ArtifactName: 'drop'
